
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egkvrsqpctgcsiqzqdba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVna3Zyc3FwY3RnY3NpcXpxZGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTE5NzMsImV4cCI6MjA2MTM4Nzk3M30.67XSUEvyAF-WJSBiiOvywsHDTduCR8Mo-eAmxCBQg6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage,
    }
  }
);
